delete-objects script and full check

diff --git a/s3/bash-scripts/delete-bucket b/s3/bash-scripts/delete-bucket
--- a/s3/bash-scripts/delete-bucket
+++ b/s3/bash-scripts/delete-bucket
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Exit immediately if a command returns a non-zero status
+set -e
+
 # Print a message indicating the delete of the bucket creation process
 echo "== delete bucket"
 
diff --git a/s3/bash-scripts/list-object b/s3/bash-scripts/list-object
--- a/s3/bash-scripts/list-object
+++ b/s3/bash-scripts/list-object
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Exit immediately if a command returns a non-zero status
+set -e
+
 # Print a message indicating the start of the list object process
 echo "== List objects in the bucket"
 
