delete-objects script and full check

diff --git a/s3/bash-scripts/list-buckets b/s3/bash-scripts/list-buckets
--- a/s3/bash-scripts/list-buckets
+++ b/s3/bash-scripts/list-buckets
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 
+# Exit immediately if a command returns a non-zero status
+set -e
+
 echo "== list newest buckets"
 
 aws s3api list-buckets | jq -r '.Buckets | sort_by(.CreationDate) | reverse | .[0:5] | .[] | .Name'
